Import-Module "$PSScriptRoot/../bin/Debug/pwsh-prompt/pwsh-prompt.psd1" -Force -DisableNameChecking -ErrorAction SilentlyContinue

$Databases = @(
	@{ Value = "Redis";       HelpMessage = "Fast in-memory cache";   Description = "🔴 In-memory key-value store originally developed by Salvatore Sanfilippo.`nSupports pub/sub, streams, sorted sets, hyperloglogs, and geospatial indexes.`nIdeal for caching, session storage, real-time leaderboards, and rate limiting.`nCan be configured for persistence via RDB snapshots or AOF append-only files.`nRedis Cluster provides automatic partitioning across multiple nodes.`nSupports Lua scripting for atomic multi-step operations.`nRedis Sentinel provides high availability through automatic failover.`nThe RESP protocol makes it easy to build clients in any language.`nRecent versions added Redis Functions as a more structured alternative to Lua scripts.`nRedis Stack extends the core with modules for JSON, search, time series, and graph queries." }
	@{ Value = "PostgreSQL";  HelpMessage = "Relational DB";          Description = "🐘 Advanced open-source relational database with over 35 years of active development.`nFull SQL compliance with powerful extensions like JSONB, arrays, and range types.`nExtensible with custom types, operators, functions, and extensions like PostGIS for geospatial data.`nMVCC concurrency model allows readers to never block writers and vice versa.`nSupports table partitioning, parallel queries, and JIT compilation for complex analytical workloads.`nBuilt-in logical and streaming replication for high availability setups.`nForeign data wrappers allow querying external data sources like MySQL, MongoDB, or flat files as if they were local tables.`nRich ecosystem of extensions: pg_stat_statements for query analysis, pgvector for AI embeddings 🤖, TimescaleDB for time series ⏱️.`nSupports row-level security policies for multi-tenant applications.`nFull-text search with tsvector and tsquery eliminates the need for external search engines in many cases." }
	@{ Value = "Azure Cosmos DB with Multi-Region Write and Automatic Failover"; HelpMessage = "Globally distributed, multi-model database service by Microsoft Azure with turnkey global distribution and five consistency models"; Description = "🌍 Fully managed NoSQL and relational database for modern app development.`nGuarantees single-digit millisecond reads and writes at the 99th percentile.`nOffers five well-defined consistency levels: strong, bounded staleness, session, consistent prefix, and eventual.`nMulti-model support including document, key-value, graph, and column-family via native APIs.`nAutomatic and instant scalability with serverless and provisioned throughput modes.`nIntegrated with Azure Functions, Azure Synapse Analytics, and Azure AI Search for end-to-end solutions." }
	@{ Value = "MongoDB";     HelpMessage = "Document store";         Description = "🍃 Document-oriented NoSQL database that stores data as flexible BSON documents.`nSchema-less design allows fields to vary between documents in the same collection.`nIdeal for unstructured or rapidly evolving schemas where relational modeling is impractical.`nSupports horizontal scaling via automatic sharding across commodity hardware.`nThe aggregation pipeline provides a powerful framework for data transformation and analysis.`nChange streams enable real-time reactive applications by watching for document modifications.`nAtlas Search integrates Apache Lucene-based full-text search directly into the database.`nMulti-document ACID transactions have been supported since version 4.0.`nTime series collections optimize storage and queries for IoT 📡 and metrics data." }
	@{ Value = "SQLite";      HelpMessage = "Embedded DB";            Description = "📦 Lightweight embedded relational database that runs in-process with zero configuration.`nNo separate server — the entire database is a single cross-platform file.`nPerfect for mobile apps 📱, CLI tools, desktop applications, and prototyping.`nUsed internally by every Android and iOS device, most web browsers, and countless embedded systems.`nSupports most of SQL92 with common table expressions, window functions, and JSON operators.`nWAL mode enables concurrent readers with a single writer for improved throughput.`nThe database file format is stable and backwards-compatible — files created in 2004 still work today.`nExtremely well-tested with 100% branch coverage and billions of tests in the test harness." }
	@{ Value = "MySQL";       HelpMessage = "Popular relational DB";  Description = "🐬 Widely-used open-source relational database that powered the early web.`nGreat for web applications and read-heavy workloads with InnoDB storage engine.`nSupports replication topologies including source-replica and group replication.`nThe MySQL Shell provides advanced admin operations and scripting in Python and JavaScript." }
	@{ Value = "Cassandra";   HelpMessage = "Wide-column store";      Description = "👁️ Distributed wide-column NoSQL database designed for high availability with no single point of failure.`nExcels at write-heavy workloads across multiple data centers with tunable consistency levels.`nUses a masterless ring architecture where every node can accept reads and writes.`nCQL query language provides a familiar SQL-like interface for developers." }
	@{ Value = "DynamoDB";    HelpMessage = "AWS managed NoSQL";      Description = "⚡ Fully managed key-value and document database service by AWS.`nSingle-digit millisecond performance at any scale with automatic scaling.`nPay-per-request or provisioned capacity pricing models.`nGlobal tables provide multi-region, multi-active replication." }
	@{ Value = "Neo4j";       HelpMessage = "Graph database";         Description = "🕸️ Native graph database for highly connected data.`nUses Cypher query language for expressive pattern matching across relationships.`nIdeal for social networks 👥, fraud detection 🔍, recommendation engines, and knowledge graphs.`nThe property graph model stores data as nodes, relationships, and properties on both.`nNative graph storage engine optimized for traversing relationships at constant time per hop.`nSupports full-text indexing, spatial queries, and graph data science algorithms.`nGraph Data Science library includes PageRank, community detection, node similarity, and pathfinding.`nAURA cloud service ☁️ provides fully managed Neo4j instances with automatic backups and scaling." }
)

$Result = Prompt-Choice $Databases `
	-Message @{ Text = "Pick a database for the project"; Style = "Bold" } `
	-Title @{ Text = "Database Picker"; Style = "Bold,Underline" }

if ($null -eq $Result) {
	Write-Host "`n  Cancelled!" -ForegroundColor DarkGray
	return
}

$Db = $Databases[$Result[0]].Value
Write-Host ""
Write-Host "  Selected: $Db" -ForegroundColor Green
Write-Host ""
